### ISSUE TITLE
Add Custom Block Support for eco plugins

### ISSUE THREAD

**Issue by lucian929** [Auxilor/eco#247]
**Is your feature request related to a problem? Please describe.**
I was considering purchasing a few plugins from the eco suite, but currently custom block support for things like enchantments is not supported. This makes it hard for us to use EcoEnchantments, because it would not integrate smoothly into our server.

**Describe the solution you'd like**
I'd like Eco to support custom blocks for any instances where blocks could be used - like material lists for enchantments.

I saw this enchantment on lrcdb:

```yaml
  effects:
  - args:
      duration: 20 * (%level% + 1)
      radius: 8 + 2 * %level%
      colors:
        redstone_ore: red
        deepslate_emerald_ore: green
        diamond_ore: aqua
        deepslate_lapis_ore: blue
        deepslate_coal_ore: black
        deepslate_diamond_ore: aqua
        copper_ore: gold
        gold_ore: yellow
        deepslate_redstone_ore: red
        iron_ore: gray
        deepslate_copper_ore: gold
        ancient_debris: dark_red
        lapis_ore: blue
        coal_ore: black
        deepslate_iron_ore: gray
        deepslate_gold_ore: yellow
        emerald_ore: green
    id: glow_nearby_blocks
```

Imagine if here you could put something like `oraxen:my_awesome_ore`, or if not that, the option to specify the blockstates for a block (like note_block[instrument=banjo,note=2]

**Describe alternatives you've considered**
No alternatives in mind currently

**Additional context**
Let me know if you have any questions!
